version: "3.2"
services:
  conductor:
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      worker:
        condition: service_started
